CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "mail" varchar(50) UNIQUE,
  "password" varchar(30) NOT NULL,
  "age" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "user_role" (
  "user_id" int NOT NULL,
  "role_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" text NOT NULL,
  "level_id" int NOT NULL,
  "teacher_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "levels" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(15) UNIQUE NOT NULL
);

CREATE TABLE "category_course" (
  "category_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) NOT NULL,
  "url" varchar(50) UNIQUE NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses_students" (
  "student_id" int NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "user_role" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_role" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "courses_students" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id");

ALTER TABLE "courses_students" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "levels" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "category_course" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "category_course" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "videos" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

INSERT INTO users (name,mail,password,age) VALUES ('josue','thejosuescript@gmail.com','password1',20),('brandon','brandon@gmail.com','password2','10');

INSERT INTO roles (role) VALUES ('student'),('teacher'),('admin');

INSERT INTO user_role VALUES ('1','2'),('2','1'),('1','3');

INSERT INTO levels (level) VALUES ('noob'),('middle'),('expert');

INSERT INTO courses (title,description,level_id,teacher_id) VALUES 
('javascript course','javascript course for beginners',1,1),
('react course','react course for beginners',1,1);

INSERT INTO categories (name) VALUES ('react'),('javascript'),('sql'),('python'),('ruby'),('free');

INSERT INTO category_course VALUES (6,1),(2,1),(1,2);

INSERT INTO videos (title,url,course_id) VALUES 
('javascript intro','https://www.coursesapp.com/c/javascript/v1.mp4',1),
('react intro','https://www.coursesapp.com/c/react/v1.mp4',2);

SELECT roles.role,users.name AS usuario 
from user_role JOIN roles ON user_role.role_id=roles.id JOIN users ON user_id=users.id;

SELECT courses.title,courses.description,levels.level,users.name AS teacher 
from courses JOIN levels ON level_id=levels.id JOIN users ON users.id=courses.teacher_id;

SELECT videos.title AS video ,courses.title AS course_name,levels.level,users.name AS teacher 
from videos JOIN courses ON courses.id=videos.course_id JOIN users ON users.id=courses.teacher_id JOIN levels ON levels.id=courses.level_id;
